### ISSUE TITLE
New Vac site bugs and fixes

### ISSUE THREAD

**Issue by oskarth** [vacp2p/vacp2p.github.io#3]
Some things that was noticed when https://github.com/vacp2p/vacp2p.github.io/pull/2 went live

- [x] https://vac.dev/research-log/ 404s
- [x] Telegram link body says Discord and has wrong logo
- [x] vac overview 404

cc @NistorCristian 

cc @j-zerah @decanus if you notice other stuff

**Comment by oskarth** [comment]
Thanks, fixed!

**Comment by oskarth** [comment]
@NistorCristian hm, found a new one. When you click 'learn more' it 404s at vac-overview

![image](https://user-images.githubusercontent.com/1552237/69423204-73db6100-0d60-11ea-81e0-2afe7d285a58.png)


However, clicking overview post from research log  goes to https://vac.dev/vac-overview and it works

**Comment by oskarth** [comment]
Another thing

![image](https://user-images.githubusercontent.com/1552237/69602515-cb284c80-1052-11ea-93a9-e4728d9782e7.png)
shows data sync twice, the bottom row should be removed
![image](https://user-images.githubusercontent.com/1552237/69602521-d54a4b00-1052-11ea-9357-e9995f56006f.png)

**Comment by NistorCristian** [comment]
#6 Done here
